### ISSUE TITLE
Count duplicate selectors

### ISSUE THREAD

**Issue by hoffi** [cssstats/cssstats#157]
Count how many times a selector is declared more than once.

E.g.
```css
.box { background-color: #ccc; }
.box { border: 1px solid black; }
```
