### ISSUE TITLE
Pasting specific input doesn't work

### ISSUE THREAD

**Issue by kelunik** [cssstats/cssstats#82]
Pasting the following content results in just reloading the page without results:

``` css
a { color: #fff; }
i { color: #ffffff; }
b { color: white; }
```

Somehow, the following works:

``` css
a { color: #fff; } i { color: #ffffff; } b { color: white; }
```
