### ISSUE TITLE
Declarations per ruleset is wrong

### ISSUE THREAD

**Issue by necolas** [cssstats/cssstats#85]
When counting the number of declarations in a rule, the tool is not distinguishing between declarations and comments on a new line. For example, this input:

``` css
.selector {
    box-sizing: border-box; /* 1 */
    list-style: none;  /* 2 */
}
```

Is output as follows (this is because `css-statistics` is using the `css` module, which doesn't preserve source whitespace):

``` css
.selector {
    box-sizing: border-box;
/* 1 */
    list-style: none; 
/* 2 */
}
```

And seems to be reported as 4 declarations rather than 2.

While you could patch this, it might be worth looking into using `postcss` which has quite detailed whitespace preservation built into the parser.

cc @jxnblk
